export interface TextInputsInt {
  onSubmit?: () => void,
  navigations?: () => void,
  onChange: ( value: string, field: string | any ) => void,
  nombre?: string,
  email?: string,
  password?: string,
  title?: string,
  buttonTitle?: string,
  message?: string,
  colors?: string,
  buttonColor?: string,
  messageColor?: string,
  buttonNext?: string,
  showNameInput?: boolean,
  showEmailInput?: boolean,
  onlyInput?: boolean,
}